### ISSUE TITLE
Vagrant: Curl not installed (Jessie)

### ISSUE THREAD

**Issue by lbischof** [antoiner77/caddy-ansible#20]
The final health check hangs when provisioning the Debian Jessie Vagrant machine, because curl isn't installed.

**Comment by kjagiello** [comment]
I've solved it by putting following into test.yml:

```yml
---
- hosts: all
  become: yes
  tasks:
    - name: Install curl
      package: name=curl state=latest
  roles:
    - caddy
```

It requires however Ansible 2.
